/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Analyze a TypeScript/JavaScript file and return per-function control flow graphs.
 *
 * This is the single synchronous entry point called from the parse worker thread.
 * It is stateless — each call performs a complete parse + semantic analysis from scratch.
 *
 * # Arguments
 *
 * * `filename` — File path (used to infer source type if `options.source_type` is not set).
 * * `source_code` — Full source text of the file.
 * * `options` — Optional configuration.
 *
 * # Returns
 *
 * A `CfgAnalysisResult` containing:
 * - `functions`: Per-function CFG data (blocks + edges).
 * - `errors`: Non-fatal parse/semantic errors. Partial results may still be present.
 */
export declare function analyzeCfg(filename: string, sourceCode: string, options?: CfgOptions | undefined | null): CfgAnalysisResult

export interface CfgAnalysisResult {
  functions: Array<FunctionCfg>
  errors: Array<CfgError>
}

export interface CfgBlock {
  id: number
  instructions: Array<CfgInstruction>
  unreachable: boolean
}

export interface CfgEdge {
  source: number
  target: number
  type: string
  conditionText?: string
}

export interface CfgError {
  message: string
  startLine: number
  endLine: number
}

export interface CfgInstruction {
  kind: string
  startLine?: number
  endLine?: number
  startColumn?: number
  endColumn?: number
  text?: string
}

export interface CfgOptions {
  /**
   * Source type override. Default: inferred from filename extension.
   * Accepted values: "typescript" | "javascript" | "tsx" | "jsx"
   */
  sourceType?: string
  /** Include instruction text for Statement instructions (default: false). */
  includeStatementText?: boolean
  /** Max functions to analyze per file (default: 500 — safety valve for generated code). */
  maxFunctions?: number
}

export interface FunctionCfg {
  name: string
  startLine: number
  endLine: number
  className?: string
  blocks: Array<CfgBlock>
  edges: Array<CfgEdge>
}
